[package]
name = "hok"
description = "Hok is a CLI implementation of Scoop in Rust"
homepage = "https://github.com/chawyehsu/hok"
version = "0.1.0-beta.3"
authors = ["Chawye Hsu <su+cratesio@chawyehsu.com>"]
license = "Apache-2.0"
edition = "2021"
readme = "README.md"

[workspace]
members = ["crates/libscoop", "crates/scoop_hash"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "hok"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.3", features = ["wrap_help", "cargo"] }
crossterm = "0.26"
env_logger = "0.8.3"
indicatif = "0.17.5"
regex = "1.5.3"
remove_dir_all = "0.7.0"
sysinfo = "0.29"

[dependencies.libscoop]
version = "0.1.0-beta.3"
features = ["rustcrypto-hash"]
path = "./crates/libscoop"

[profile.release]
lto = "fat"
panic = "abort"
opt-level = "z"
codegen-units = 1
