cargo-features = ["strip"]

[package]
name = "scoop"
description = "The Scoop Windows command line installer rewritten in Rust"
homepage = "https://github.com/chawyehsu/scoop-rs"
version = "0.1.0"
authors = ["Chawye Hsu <chawyehsu@hotmail.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
anyhow = "1.0.40"
chrono = "0.4.19"
clap = "2.33.3"
dirs = "3.0.1"
futures = "0.3.14"
git2 = "0.13.17"
glob = "0.3.0"
once_cell = "1.7.2"
regex = "1.5.3"
remove_dir_all = "0.7.0"
serde_json = "1.0.64"
ureq = { version = "2.1.1", features = ["json"] }

# [profile.dev]
# panic = "abort"

[profile.release]
lto = true
strip = "symbols"
panic = "abort"
opt-level = "z"
codegen-units = 1
