cargo-features = ["strip"]

[package]
name = "scoop"
description = "The Scoop Windows command line installer rewritten in Rust"
homepage = "https://github.com/chawyehsu/scoop-rs"
version = "0.1.0"
authors = ["Chawye Hsu <chawyehsu@hotmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
clap = "2.33.3"
dirs = "3.0.1"
git2 = "0.13.17"
glob = "0.3.0"
lazy_static = "1.4.0"
remove_dir_all = "0.7.0"
serde_json = "1.0.64"

# [profile.dev]
# panic = "abort"

[profile.release]
lto = true
strip = "symbols"
panic = "abort"
opt-level = "z"
codegen-units = 1
